modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "need_to_sleep"
version = "${version}"
displayName = "Need to Sleep"
authors = "Vico Shortman"
description = '''
Adds a system, that forces the player to sleep after some time.
'''
#logoFile = ""

[[dependencies.need_to_sleep]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.need_to_sleep]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.need_to_sleep]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "need_to_sleep.mixins.json"
